export {
  emailSchema,
  passwordSchema,
  nameSchema,
  PasswordLoginSchema,
  MagicLinkSchema,
  PasswordSignUpSchema,
  ForgotPasswordSchema,
  ResetPasswordSchema,
  type PasswordLoginData,
  type MagicLinkData,
  type PasswordSignUpData,
  type ForgotPasswordData,
  type ResetPasswordData,
} from "./auth.schema";
