import { internalMutation, internalQuery } from "../_generated/server";
import { v } from "convex/values";

/**
 * Stores a real OTP generated by Better Auth for a test email address.
 * Called from the emailOTP sendVerificationOTP callback when PLAYWRIGHT_TEST_SECRET is set.
 * The test-session route reads this value back via readTestOtp to complete the sign-in flow.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const storeTestOtp = internalMutation({
  args: {
    email: v.string(),
    otp: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        otp: args.otp,
        createdAt: Date.now(),
      });
    } else {
      await ctx.db.insert("testOtpStore", {
        email: args.email,
        otp: args.otp,
        createdAt: Date.now(),
      });
    }

    return null;
  },
});

/**
 * Reads the stored OTP for a test email address.
 * Called from the /test/read-otp HTTP action so the test-session route can complete sign-in.
 *
 * WARNING: Only valid for emails ending in @mirror.test. Never expose as public API.
 */
export const readTestOtp = internalQuery({
  args: {
    email: v.string(),
  },
  returns: v.union(v.string(), v.null()),
  handler: async (ctx, args) => {
    const record = await ctx.db
      .query("testOtpStore")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    return record?.otp ?? null;
  },
});

/**
 * Upserts the app-level users row for a test user.
 * Sets username, name, and onboardingComplete so tests can proceed past onboarding.
 *
 * WARNING: Only call from test infrastructure. Never expose as public API.
 */
export const ensureTestUser = internalMutation({
  args: {
    email: v.string(),
    username: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("users")
      .withIndex("by_email", (q) => q.eq("email", args.email))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    } else {
      await ctx.db.insert("users", {
        authId: `test_${args.email}`,
        email: args.email,
        username: args.username,
        name: "Test User",
        onboardingComplete: true,
      });
    }

    return null;
  },
});
